package pract1;
// Generated 8/03/2016 04:49:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contrasenia generated by hbm2java
 */
public class Contrasenia  implements java.io.Serializable {


     private int idcontrasenia;
     private String contrasenia;
     private Set usuarios = new HashSet(0);

    public Contrasenia() {
    }

	
    public Contrasenia(int idcontrasenia) {
        this.idcontrasenia = idcontrasenia;
    }
    public Contrasenia(int idcontrasenia, String contrasenia, Set usuarios) {
       this.idcontrasenia = idcontrasenia;
       this.contrasenia = contrasenia;
       this.usuarios = usuarios;
    }
   
    public int getIdcontrasenia() {
        return this.idcontrasenia;
    }
    
    public void setIdcontrasenia(int idcontrasenia) {
        this.idcontrasenia = idcontrasenia;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

     public String toString() {
        return this.contrasenia;
    }


}


