package pract1;
// Generated 8/03/2016 04:49:39 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private Contrasenia contrasenia;
     private String unombre;
     private String uapp;
     private String uapm;

    public Usuario() {
    }

	
    public Usuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Usuario(int idusuario, Contrasenia contrasenia, String unombre, String uapp, String uapm) {
       this.idusuario = idusuario;
       this.contrasenia = contrasenia;
       this.unombre = unombre;
       this.uapp = uapp;
       this.uapm = uapm;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Contrasenia getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(Contrasenia contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getUnombre() {
        return this.unombre;
    }
    
    public void setUnombre(String unombre) {
        this.unombre = unombre;
    }
    public String getUapp() {
        return this.uapp;
    }
    
    public void setUapp(String uapp) {
        this.uapp = uapp;
    }
    public String getUapm() {
        return this.uapm;
    }
    
    public void setUapm(String uapm) {
        this.uapm = uapm;
    }

    public String toString() {
        return this.idusuario + " , " + this.unombre + " , " + this.uapp + " , " + this.uapm;
    }


}


